<?php

namespace OnlineShopBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function loadUserByUsername($username)
    {
        return $this->findOneBy(
            [
                'username' => $username
            ]
        );
    }
}
